apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/app-config.yaml
  - infra/mysql-external.yaml
  - infra/nacos.yaml
  - infra/rocketmq.yaml
  - apps/customer-service.yaml
  - apps/account-service.yaml
  - apps/api-gateway.yaml
