package com.example.bank.common.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public abstract class BaseRequestDTO {

    /**
     * Global serial number generated by the upstream caller.
     * It is the idempotency key for external requests.
     */
    @NotBlank(message = "Global serial number is required")
    private String globalSerialNo;
}
