apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: ghcr.io/xiaopanyz-max/bank-customer-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: bank-app-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/bank_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bank-local-secrets
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-local-secrets
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: bank
spec:
  selector:
    app: customer-service
  ports:
    - port: 8082
      targetPort: 8082
